name: DKLib
version: 1.1.2
description: a usefull Lib with a lot of helpfull utils
author: michidk
website: https://github.com/michidk/DKLib

main: me.michidk.DKLib.Main
softdepend: [ProtocolLib]

commands:
  DKLib:
    description: test command